/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Return the caller's display-ready dashboard. Requires a valid bearer token.
         *
         *     A missing/failed discovery session degrades to an empty progress meter; a
         *     transient workspace fault degrades to an empty workspace. A schema
         *     ``ContractVersionError`` propagates.
         */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio
         * @description Return the caller's display-ready portfolio. Requires a valid bearer token.
         *
         *     A missing/failed discovery session degrades to an empty portfolio payload.
         */
        get: operations["portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jobs
         * @description Return the caller's persisted job matches. Requires a valid bearer token.
         *
         *     Shows previously-accepted jobs minus dismissed companies. No persisted jobs —
         *     or a transient ledger fault — yields an empty typed payload (never a 500).
         */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Profile Endpoint
         * @description Persist the caller's résumé-header profile and return the re-read value.
         *
         *     Requires a valid bearer token. The sync store write + re-read run in a
         *     threadpool. Returns the profile as it was persisted (round-trip), so the
         *     client sees exactly what was stored.
         */
        post: operations["save_profile_endpoint_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Preferences Endpoint
         * @description Persist the caller's discovery preferences and return the re-read value.
         *
         *     Requires a valid bearer token. The sync store write + re-read run in a
         *     threadpool. Returns the preferences as they were persisted (round-trip).
         */
        put: operations["save_preferences_endpoint_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Application Endpoint
         * @description Record a tailored application and return the created :class:`Application`.
         *
         *     Requires a valid bearer token. ``applied_on`` is the injected clock
         *     (``date.today()``) computed at this boundary — never read inside the store. The
         *     sync store write runs in a threadpool.
         */
        post: operations["save_application_endpoint_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Experience Endpoint
         * @description Append a manual experience to the caller's canonical discovery session.
         *
         *     Requires a valid bearer token. ``reference_date`` is the injected clock
         *     (``date.today()``) computed at this boundary. The async session write and the
         *     subsequent best-effort re-read are awaited natively (no sync bridge). The
         *     response confirms the persisted entry re-read from the session; if the re-read
         *     can't find it (or the session can't be loaded), the ``entry_id`` is still echoed
         *     with the submitted ``title``/``org`` rather than a 500.
         */
        post: operations["add_experience_endpoint_api_experience_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Grill Action
         * @description Record the caller's grill input into the durable session WITHOUT running the graph.
         *
         *     Requires a valid bearer token. Dispatches on ``body.action``:
         *     ``start`` creates the session from ``history`` (with an injected ``reference_date``
         *     default of today), ``answer`` records ``pending_user_answer``, ``confirm`` records
         *     ``checkpoint_verified``. Returns a small status snapshot read AFTER the record so
         *     the client can render the banner + await state before opening the SSE stream. A
         *     malformed body / bad ``action`` yields 422 automatically. ``start`` with an
         *     empty ``history`` and ``answer`` with an empty ``answer`` are also rejected with
         *     422 (recording a turn with no user input is a client error, not a valid state).
         */
        post: operations["record_grill_action_api_grill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grill/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Grill Turns
         * @description Run the pending turn sequence and stream one ``event: turn`` per completed turn.
         *
         *     Requires a valid bearer token. The async generator runs the first (pre-recorded)
         *     turn, then auto-advances — but ONLY after a story is accepted — bounded by
         *     ``_MAX_AUTO_TURNS``, stopping on next-question / checkpoint / complete / upgrade
         *     (mirrors ``web/grill_ui._submit_answer`` exactly). Each completed turn is emitted
         *     as an ``event: turn`` frame; a terminal ``event: done`` carries the final turn. A
         *     :class:`ModelAPIError` mid-stream is caught and emitted as ``event: error`` instead
         *     of 500-ing the response.
         */
        get: operations["stream_grill_turns_api_grill_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tailor
         * @description Tailor the caller's portfolio to a JD and return the structured résumé.
         *
         *     Requires a valid bearer token AND a BYOK key (``get_discovery_session`` → 409 if
         *     no key). One model call runs on the user's own quota. The tailored résumé is
         *     returned for preview; it is not persisted (persistence happens only when the client
         *     saves it as an application via ``POST /api/applications``).
         */
        post: operations["tailor_api_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Resume
         * @description Render a structured résumé (from the body) to the requested format's bytes.
         *
         *     Requires a valid bearer token (``_user_id`` is injected only to enforce auth — the
         *     render itself is per-request and needs no BYOK key). An unknown ``fmt`` is rejected
         *     as 422 by the ``Literal`` path param.
         */
        post: operations["render_resume_api_resume__fmt__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a liveness signal. Unauthenticated.
         *
         *     Returns:
         *         A :class:`HealthResponse` with ``status == "ok"``.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the verified caller's identity. Requires a valid bearer token.
         *
         *     Args:
         *         identity: The verified caller identity resolved at the auth boundary.
         *
         *     Returns:
         *         A :class:`MeResponse` with the stable ``user_id`` and, when present, the
         *         caller's email. The raw token is never returned.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Application
         * @description A single tracked job application (no secrets/PII beyond what the user enters).
         */
        Application: {
            /**
             * Application Id
             * Format: uuid
             * @description Stable identifier
             */
            application_id?: string;
            /**
             * Company
             * @description Employer / organisation name
             * @default
             */
            company: string;
            /**
             * Job Title
             * @description Role title applied for
             * @default
             */
            job_title: string;
            /**
             * @description Application lifecycle status
             * @default applied
             */
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Applied On
             * @description ISO date (YYYY-MM-DD) the application was submitted; set at the boundary, never via datetime.now() in logic. Drives the 14-day sweep.
             * @default
             */
            applied_on: string;
            /**
             * Jd Text
             * @description Cleaned job-description text this application was tailored against
             * @default
             */
            jd_text: string;
            /**
             * Tailored Resume Json
             * @description The tailored resume variant used for this application (JSON)
             * @default
             */
            tailored_resume_json: string;
        };
        /**
         * ApplicationStatus
         * @description Lifecycle status of a tracked job application.
         * @enum {string}
         */
        ApplicationStatus: "applied" | "interview" | "offer" | "rejected" | "withdrawn";
        /**
         * ApplicationWriteRequest
         * @description Request body for ``POST /api/applications`` (api-local, not ``schema.py``).
         *
         *     A strict, no-extra-fields DTO the endpoint maps onto the existing
         *     ``web.application_store.save_tailored_application`` seam. ``applied_on`` is NOT
         *     part of the request: it is the injected clock computed at the endpoint boundary
         *     (``datetime.date.today()``), never supplied by the caller.
         */
        ApplicationWriteRequest: {
            /** Company */
            company: string;
            /** Job Title */
            job_title: string;
            /** Jd Text */
            jd_text: string;
            /** Tailored Resume Json */
            tailored_resume_json: string;
        };
        /**
         * ContactDTO
         * @description Résumé header identity (mirrors ``web.resume_builder.Contact``).
         */
        ContactDTO: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Links */
            links?: string[];
        };
        /**
         * DashboardResponse
         * @description Mirror of :class:`web.dashboard.DashboardView` (display-ready).
         */
        DashboardResponse: {
            /** Progress Meter */
            progress_meter: string;
            /** Show Nudge */
            show_nudge: boolean;
            /** Nudge Message */
            nudge_message: string;
            /** Pending Actions */
            pending_actions: string[];
            /** Application Count */
            application_count: number;
            /** Can Tailor */
            can_tailor: boolean;
            /** Can Start Grill */
            can_start_grill: boolean;
            /** Can Find Jobs */
            can_find_jobs: boolean;
            /** Pending Actions Detail */
            pending_actions_detail: {
                [key: string]: string;
            }[];
        };
        /**
         * Entry
         * @description A single career experience entry in the work timeline.
         *
         *     The grillable unit of discovery: a job, internship, project, research
         *     engagement, open-source contribution, leadership role, or education item.
         */
        Entry: {
            /**
             * Entry Id
             * Format: uuid
             * @description Stable identifier for this entry (UUID)
             */
            entry_id?: string;
            /**
             * @description Category of experience (full_time, project, education, etc.)
             * @default other
             */
            type: components["schemas"]["ExperienceType"];
            /**
             * Title
             * @description Role/project title (e.g. 'Senior Engineer', 'Capstone Project')
             */
            title: string;
            /**
             * Org
             * @description Organisation, school, or team name
             * @default
             */
            org: string;
            /**
             * Start Date
             * @description Start date in YYYY-MM or YYYY format; empty means unknown
             * @default
             */
            start_date: string;
            /**
             * End Date
             * @description End date in YYYY-MM or YYYY format; empty string means 'present'
             * @default
             */
            end_date: string;
            /**
             * Source
             * @description How this entry entered the timeline
             * @default manual
             * @enum {string}
             */
            source: "resume" | "discovered" | "manual";
            /**
             * Bullets
             * @description Existing resume bullets or notes for this entry
             */
            bullets?: string[];
            /**
             * @description Processing status of this entry in the discovery pipeline
             * @default needs_quantifying
             */
            status: components["schemas"]["EntryStatus"];
            /**
             * Highlighted
             * @description User pinned this experience as tailoring priority (4E, additive v2.7.0): its quantified achievements are always included when tailoring to a JD.
             * @default false
             */
            highlighted: boolean;
        };
        /**
         * EntryCardResponse
         * @description Mirror of :class:`web.portfolio.EntryCard`.
         */
        EntryCardResponse: {
            /** Entry Id */
            entry_id: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Dates */
            dates: string;
            /** Type Label */
            type_label: string;
            /** Status Label */
            status_label: string;
            /** Bullets */
            bullets: string[];
            /** Stories */
            stories: components["schemas"]["StoryCardResponse"][];
            /** Highlighted */
            highlighted: boolean;
            /** Story Count */
            story_count: number;
            /** Stories Target */
            stories_target: number;
        };
        /**
         * EntryStatus
         * @description Processing status of an experience entry in the discovery pipeline.
         * @enum {string}
         */
        EntryStatus: "documented" | "needs_quantifying" | "grilled" | "summarized" | "skipped";
        /**
         * ExperienceType
         * @description Type of career experience entry being tracked.
         * @enum {string}
         */
        ExperienceType: "full_time" | "internship" | "project" | "research" | "open_source" | "leadership" | "part_time" | "education" | "other";
        /**
         * ExperienceWriteResponse
         * @description Response for ``POST /api/experience`` (api-local, not ``schema.py``).
         *
         *     Confirms the persisted manual entry by echoing its ``entry_id`` and the
         *     ``title``/``org`` re-read from the discovery session, plus the resulting
         *     ``entry_count``. If the write can't be re-read, the endpoint still returns the
         *     echoed ``entry_id`` (with the submitted ``title``/``org``) rather than 500.
         */
        ExperienceWriteResponse: {
            /** Entry Id */
            entry_id: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Entry Count */
            entry_count: number;
        };
        /**
         * GrillActionRequest
         * @description Request body for ``POST /api/grill`` (api-local, not ``schema.py``).
         *
         *     Records the caller's input into the durable canonical session WITHOUT running
         *     the graph (the graph runs later on ``GET /api/grill/stream``). The user's answer
         *     travels in the body (never a URL query), so grill PII never lands in access logs.
         *
         *     - ``start`` uses ``history`` (+ optional ``reference_date``) to create the session.
         *     - ``answer`` uses ``answer`` (patched as ``pending_user_answer``).
         *     - ``confirm`` uses neither (sets ``checkpoint_verified``).
         */
        GrillActionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "answer" | "confirm";
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * History
             * @default
             */
            history: string;
            /**
             * Reference Date
             * @default
             */
            reference_date: string;
        };
        /**
         * GrillSnapshot
         * @description Response for ``POST /api/grill``: a small post-record status snapshot.
         *
         *     Computed from the durable session AFTER the record (no turn was run), so the
         *     client can render the "currently grilling" banner + await state before opening
         *     the SSE stream.
         */
        GrillSnapshot: {
            /** Phase */
            phase: string;
            /** Frontier Label */
            frontier_label: string;
            /**
             * Awaiting
             * @enum {string}
             */
            awaiting: "question" | "checkpoint" | "complete";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness response body.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * JobCardResponse
         * @description Mirror of :class:`web.jobs.JobCard`.
         */
        JobCardResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Work Model */
            work_model: string;
            /** Employment Type */
            employment_type: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * JobsResponse
         * @description Mirror of :class:`web.jobs.JobsView` (``is_empty`` included).
         */
        JobsResponse: {
            /** Accepted */
            accepted: components["schemas"]["JobCardResponse"][];
            /** For Review */
            for_review: components["schemas"]["JobCardResponse"][];
            /** Iterations */
            iterations: number;
            /** Hard Rejected Count */
            hard_rejected_count: number;
            /** Ran */
            ran: boolean;
            /** Empty Text */
            empty_text: string;
            /** Is Empty */
            is_empty: boolean;
        };
        /**
         * MeResponse
         * @description Verified identity response body (safe display info only).
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email?: string | null;
        };
        /**
         * PortfolioResponse
         * @description Mirror of :class:`web.portfolio.PortfolioView` (``is_empty`` included).
         */
        PortfolioResponse: {
            /** Entries */
            entries: components["schemas"]["EntryCardResponse"][];
            /** Empty Text */
            empty_text: string;
            /** Is Empty */
            is_empty: boolean;
        };
        /**
         * RoleBlockDTO
         * @description One experience/education entry (mirrors ``web.resume_builder.RoleBlock``).
         */
        RoleBlockDTO: {
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Dates */
            dates: string;
            /** Bullets */
            bullets?: string[];
        };
        /**
         * SessionPreferences
         * @description The evaluation rubric for a discovery session (gathered at intake).
         *
         *     ``dealbreakers`` are absolute (→ HARD_REJECT); ``nice_to_haves`` are soft
         *     (a miss → SOFT_REJECT, kept for review). No secrets. Persisted per user on
         *     ``UserWorkspace.discovery_preferences`` (v2.8.0) so it isn't re-entered.
         */
        SessionPreferences: {
            /**
             * Target Roles
             * @description Roles being targeted this session
             */
            target_roles?: string[];
            /**
             * Dealbreakers
             * @description Absolute exclusions (e.g. 'W2 only', 'on-site', 'no cloud')
             */
            dealbreakers?: string[];
            /**
             * Nice To Haves
             * @description Soft preferences (a miss is a SOFT_REJECT, not a drop)
             */
            nice_to_haves?: string[];
            /**
             * Contract Version
             * @default 2.8.0
             */
            contract_version: string;
        };
        /**
         * StoryCardResponse
         * @description Mirror of :class:`web.portfolio.StoryCard`.
         */
        StoryCardResponse: {
            /** Situation */
            situation: string;
            /** Task */
            task: string;
            /** Action */
            action: string;
            /** Result */
            result: string;
            /** Metric Validated */
            metric_validated: boolean;
            /** Story Id */
            story_id: string;
        };
        /**
         * StructuredResumeDTO
         * @description A real résumé (mirrors ``web.resume_builder.StructuredResume``).
         *
         *     Response of ``POST /api/tailor`` and request body of ``POST /api/resume/{fmt}``.
         */
        StructuredResumeDTO: {
            contact: components["schemas"]["ContactDTO"];
            /** Summary */
            summary: string;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["RoleBlockDTO"][];
            /** Education */
            education?: components["schemas"]["RoleBlockDTO"][];
        };
        /**
         * TailorRequest
         * @description Request body for ``POST /api/tailor``.
         *
         *     ``jd_text`` is the already-resolved job description; ``instructions`` are placed
         *     in the *user* prompt (injection-safe, per 9I) and never persisted; ``contact``
         *     optionally overrides the résumé header (else an empty header).
         */
        TailorRequest: {
            /** Jd Text */
            jd_text: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            contact?: components["schemas"]["ContactDTO"] | null;
        };
        /**
         * UserProfile
         * @description The user's résumé-header identity, persisted so it isn't re-entered.
         *
         *     Sourced from what the user types in the Tailor contact form (and, later, from
         *     résumé parsing). Contains only self-provided contact details — no secrets, no
         *     BYOK key. Optional/empty for a new user.
         */
        UserProfile: {
            /**
             * Name
             * @description Full name for the résumé header
             * @default
             */
            name: string;
            /**
             * Email
             * @description Contact email
             * @default
             */
            email: string;
            /**
             * Phone
             * @description Contact phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @description Location string (e.g. 'Remote · US')
             * @default
             */
            location: string;
            /**
             * Links
             * @description Profile links (LinkedIn, GitHub, portfolio)
             */
            links?: string[];
            /**
             * Contract Version
             * @default 2.8.0
             */
            contract_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_endpoint_api_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_preferences_endpoint_api_preferences_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_application_endpoint_api_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_experience_endpoint_api_experience_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Entry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_grill_action_api_grill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrillActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrillSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_grill_turns_api_grill_stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_api_tailor_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredResumeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_resume_api_resume__fmt__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                fmt: "pdf" | "docx" | "md";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredResumeDTO"];
            };
        };
        responses: {
            /** @description The rendered résumé bytes for the requested format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
