/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Return the caller's display-ready dashboard. Requires a valid bearer token.
         *
         *     A missing/failed discovery session degrades to an empty progress meter; a
         *     transient workspace fault degrades to an empty workspace. A schema
         *     ``ContractVersionError`` propagates.
         */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio
         * @description Return the caller's display-ready portfolio. Requires a valid bearer token.
         *
         *     A missing/failed discovery session degrades to an empty portfolio payload.
         */
        get: operations["portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jobs
         * @description Return the caller's persisted job matches. Requires a valid bearer token.
         *
         *     Shows previously-accepted jobs minus dismissed companies. No persisted jobs —
         *     or a transient ledger fault — yields an empty typed payload (never a 500).
         */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile
         * @description Return the caller's persisted résumé-header profile (empty for a new user).
         *
         *     Reads through :func:`_safe_load_workspace`, so it obeys this module's contract:
         *     a transient store fault degrades to an empty profile (never a 500) while a
         *     ``ContractVersionError`` still propagates. The defensive copy matches
         *     :func:`web.profile_store.load_profile` — a caller mutating the result must not
         *     write through to a cached workspace instance.
         */
        get: operations["profile_api_profile_get"];
        put?: never;
        /**
         * Save Profile Endpoint
         * @description Persist the caller's résumé-header profile and return the re-read value.
         *
         *     Requires a valid bearer token. The sync store write + re-read run in a
         *     threadpool. Returns the profile as it was persisted (round-trip), so the
         *     client sees exactly what was stored.
         */
        post: operations["save_profile_endpoint_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preferences
         * @description Return the caller's persisted discovery rubric (empty for a new user).
         *
         *     Same degrade-to-empty contract as :func:`profile` above.
         */
        get: operations["preferences_api_preferences_get"];
        /**
         * Save Preferences Endpoint
         * @description Persist the caller's discovery preferences and return the re-read value.
         *
         *     Requires a valid bearer token. The sync store write + re-read run in a
         *     threadpool. Returns the preferences as they were persisted (round-trip).
         */
        put: operations["save_preferences_endpoint_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Application Endpoint
         * @description Record a tailored application and return the created :class:`Application`.
         *
         *     Requires a valid bearer token. ``applied_on`` is the injected clock
         *     (``date.today()``) computed at this boundary — never read inside the store. The
         *     sync store write runs in a threadpool.
         */
        post: operations["save_application_endpoint_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Experience Endpoint
         * @description Append a manual experience to the caller's canonical discovery session.
         *
         *     Requires a valid bearer token. ``reference_date`` is the injected clock
         *     (``date.today()``) computed at this boundary. The async session write and the
         *     subsequent best-effort re-read are awaited natively (no sync bridge). The
         *     response confirms the persisted entry re-read from the session; if the re-read
         *     can't find it (or the session can't be loaded), the ``entry_id`` is still echoed
         *     with the submitted ``title``/``org`` rather than a 500.
         */
        post: operations["add_experience_endpoint_api_experience_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grill Status
         * @description Report whether a durable grill session already exists, so the client can RESUME.
         *
         *     Read-only: it reports what the session already holds (``current_question`` and
         *     ``checkpoint_delta_summary`` are persisted state), so it runs NO graph turn and
         *     needs NO BYOK key — and resuming can never re-ask a question the user already saw.
         *
         *     Without this the Grill page had no way to know a session existed: it decided what to
         *     render from in-memory state alone, so every fresh page load showed the "upload your
         *     résumé" start card — stranding users who had a live session, including anyone who
         *     had just clicked "Grill me about this" in the Portfolio.
         */
        get: operations["grill_status_api_grill_get"];
        put?: never;
        /**
         * Record Grill Action
         * @description Record the caller's grill input into the durable session WITHOUT running the graph.
         *
         *     Requires a valid bearer token. Dispatches on ``body.action``:
         *     ``start`` creates the session from ``history`` (with an injected ``reference_date``
         *     default of today), ``answer`` records ``pending_user_answer``, ``confirm`` records
         *     ``checkpoint_verified``. Returns a small status snapshot read AFTER the record so
         *     the client can render the banner + await state before opening the SSE stream. A
         *     malformed body / bad ``action`` yields 422 automatically. ``start`` with an
         *     empty ``history`` and ``answer`` with an empty ``answer`` are also rejected with
         *     422 (recording a turn with no user input is a client error, not a valid state).
         */
        post: operations["record_grill_action_api_grill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grill/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed From Resume
         * @description Vision-parse an uploaded résumé into a starting timeline and seed the grill.
         *
         *     Requires a valid bearer token AND a BYOK key (``get_discovery_session`` → 409). The
         *     file (PDF/PNG/JPG/WEBP) is parsed by the multimodal model on the user's OWN key
         *     (``tools.resume_parser.parse_resume``) into ``Entry`` objects — the raw bytes are
         *     never stored. Returns the post-record snapshot so the client can open the SSE stream,
         *     exactly like ``start``.
         *
         *     **A re-upload MERGES; it never clobbers (CQ-2).** Users legitimately keep several
         *     overlapping résumés. A matched role (same title + org) keeps its ``entry_id``, its
         *     STAR stories and its GRILLED status and only gains new bullets; a genuinely-new role
         *     is appended ungrilled and the grill frontier moves to it; a role this résumé happens
         *     to omit is KEPT (a résumé is a curated subset of a career, not a delete list). Only a
         *     FIRST upload — no session yet — creates one.
         */
        post: operations["seed_from_resume_api_grill_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grill/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Grill Turns
         * @description Run the pending turn sequence and stream one ``event: turn`` per completed turn.
         *
         *     Requires a valid bearer token. The async generator runs the first (pre-recorded)
         *     turn, then auto-advances — but ONLY after a story is accepted — bounded by
         *     ``_MAX_AUTO_TURNS``, stopping on next-question / checkpoint / complete / upgrade
         *     (mirrors ``web/grill_ui._submit_answer`` exactly). Each completed turn is emitted
         *     as an ``event: turn`` frame; a terminal ``event: done`` carries the final turn. A
         *     :class:`ModelAPIError` mid-stream is caught and emitted as ``event: error`` instead
         *     of 500-ing the response.
         */
        get: operations["stream_grill_turns_api_grill_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tailor
         * @description Tailor the caller's portfolio to a JD and return the structured résumé.
         *
         *     Requires a valid bearer token AND a BYOK key (``get_discovery_session`` → 409 if
         *     no key). One model call runs on the user's own quota. The tailored résumé is
         *     returned for preview; it is not persisted (persistence happens only when the client
         *     saves it as an application via ``POST /api/applications``).
         */
        post: operations["tailor_api_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master-resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Master Resume
         * @description Assemble the caller's MASTER résumé — every validated achievement, no tailoring.
         *
         *     Requires a valid bearer token but NOT a BYOK key: the assembly is deterministic
         *     (``web.resume_builder.master_structured_resume`` — no model call), so it must not be
         *     gated behind ``get_discovery_session``. A missing discovery session degrades to an
         *     empty résumé rather than an error, exactly like ``GET /api/portfolio``.
         *
         *     Returned for preview/export; not persisted (the client exports it via
         *     ``POST /api/resume/{fmt}``).
         */
        post: operations["master_resume_api_master_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Resume
         * @description Render a structured résumé (from the body) to the requested format's bytes.
         *
         *     Requires a valid bearer token (``_user_id`` is injected only to enforce auth — the
         *     render itself is per-request and needs no BYOK key). An unknown ``fmt`` is rejected
         *     as 422 by the ``Literal`` path param.
         */
        post: operations["render_resume_api_resume__fmt__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Key Status
         * @description Return whether the caller has a saved BYOK key (never the key itself).
         *
         *     Uses ``key_exists`` so the secret PAYLOAD is never pulled into memory. A genuine
         *     vault fault surfaces as 502 (not a misleading ``has_key: false``).
         */
        get: operations["key_status_api_key_get"];
        put?: never;
        /**
         * Set Key
         * @description Store the caller's Gemini key in Secret Manager. Returns 204 (no body).
         */
        post: operations["set_key_api_key_post"];
        /**
         * Remove Key
         * @description Remove the caller's saved key (idempotent). Returns 204.
         */
        delete: operations["remove_key_api_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Jobs
         * @description Run job discovery on the caller's BYOK key + saved rubric; return fresh matches.
         *
         *     409 if no BYOK key is configured (the run consumes the user's own Gemini quota).
         */
        post: operations["discover_jobs_api_jobs_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Company
         * @description Record a dismissed ("Not interested") company; future runs hard-reject it.
         *
         *     Idempotent — the ledger de-duplicates the company list. Requires a bearer token but
         *     no BYOK key (a ledger write, no model call). A ledger fault surfaces as 502 rather
         *     than a silent success, so the UI never claims a dismissal that was not persisted.
         */
        post: operations["dismiss_company_api_jobs_dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}/grill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grill Entry
         * @description Pin the grill frontier to ``entry_id`` so the next grill turn focuses on it.
         */
        post: operations["grill_entry_api_experience__entry_id__grill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}/highlight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Highlight Entry
         * @description Flip an entry's ``highlighted`` (pin) flag — pinned entries are always tailored.
         */
        post: operations["highlight_entry_api_experience__entry_id__highlight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}/bullet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Bullet
         * @description Append a new bullet to an experience — add a line without re-grilling the entry.
         *
         *     Like the PATCH twin below, the bridge treats a missing entry as a logged no-op, so
         *     the 404 fires only when the user has no discovery session at all.
         */
        post: operations["add_bullet_api_experience__entry_id__bullet_post"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Bullet
         * @description Edit one existing bullet on an experience in place.
         *
         *     The bullet is addressed by its stable ``bullet_id`` (v2.9.0), never by array index —
         *     an index shifts under any concurrent insert or delete, so a slow client could edit
         *     the wrong line. The bridge treats a missing entry or an UNKNOWN ``bullet_id`` as a
         *     logged no-op (it never raises), so those still return 204. The 404 fires only when
         *     the user has no discovery session at all (bridge returns ``None``).
         */
        patch: operations["edit_bullet_api_experience__entry_id__bullet_patch"];
        trace?: never;
    };
    "/api/experience/{entry_id}/bullet/{bullet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Bullet
         * @description Delete one bullet from an experience (CQ-3).
         *
         *     The store could replace a bullet and append one, but never remove one — edit-only is
         *     half a tool, and it matters more now that a résumé re-upload can merge in lines the
         *     user does not want. Idempotent: an unknown entry or bullet is a no-op (204). The 404
         *     fires only when the user has no discovery session at all.
         */
        delete: operations["remove_bullet_api_experience__entry_id__bullet__bullet_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Entry
         * @description Delete an experience AND every STAR story linked to it (CQ-3).
         *
         *     The cascade is deliberate: leaving the stories behind would orphan them against an
         *     ``entry_id`` that no longer exists — they would still count toward the portfolio
         *     meter and could still be selected onto a résumé under a role the user just removed.
         *     If the deleted entry was the grill frontier, the frontier is cleared so the next turn
         *     is not aimed at an experience that is gone.
         *
         *     Idempotent: an unknown entry is a no-op (204). The 404 fires only when there is no
         *     session at all.
         */
        delete: operations["remove_entry_api_experience__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/story/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Story
         * @description Delete a STAR story by id.
         *
         *     Idempotent: a missing ``story_id`` is a no-op that still returns 204. The 404 fires
         *     only when the user has no discovery session at all (bridge returns ``None``).
         */
        delete: operations["delete_story_api_story__story_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}/copywrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copywrite
         * @description Propose rewritten bullets for ONE experience (CQ-4). Nothing is persisted.
         *
         *     ONE model call on the caller's own key, batched across the whole entry — a call per
         *     bullet would make the grill interminable (AD-18.2). The user then accepts / edits /
         *     rejects each proposal; only what they accept is written back (via ``/bullets/accept``),
         *     so **no unreviewed prose can reach a PDF**.
         *
         *     Requires a BYOK key (``get_discovery_session`` → 409 without one). An unknown entry, or a
         *     model/parse failure, yields an EMPTY proposal list rather than an error: copywriting is an
         *     improvement, never a dependency, and must not be able to take the portfolio down with it.
         */
        post: operations["copywrite_api_experience__entry_id__copywrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{entry_id}/bullets/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Copywritten Bullets
         * @description Persist the rewrites the user ACCEPTED (CQ-4). No model call, no key needed.
         *
         *     A rewrite of an existing bullet SUPERSEDES it — the original is removed here, resolved by
         *     id, so the résumé can never carry both the polished line and the one it replaced. A
         *     rewrite derived from a STAR story adds a bullet the entry did not have. Rejected proposals
         *     are simply absent from the request and the original is untouched.
         *
         *     Because the accepted text is persisted, résumé export needs **no model call at all**.
         */
        post: operations["accept_copywritten_bullets_api_experience__entry_id__bullets_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a liveness signal. Unauthenticated.
         *
         *     Returns:
         *         A :class:`HealthResponse` with ``status == "ok"``.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the verified caller's identity. Requires a valid bearer token.
         *
         *     Args:
         *         identity: The verified caller identity resolved at the auth boundary.
         *
         *     Returns:
         *         A :class:`MeResponse` with the stable ``user_id`` and, when present, the
         *         caller's email. The raw token is never returned.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptBulletsRequest
         * @description Request body for ``POST /api/experience/{entry_id}/bullets/accept`` (CQ-4).
         *
         *     Only the rewrites the user actually accepted are sent. A rewrite of an existing bullet
         *     supersedes it (the original stops appearing on the résumé, resolved BY ID); a rewrite
         *     derived from a STAR story adds a bullet the entry did not have. Rejected proposals are
         *     simply absent, and the original stays untouched.
         */
        AcceptBulletsRequest: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedBullet"][];
        };
        /**
         * AcceptedBullet
         * @description One rewrite the user ACCEPTED (possibly after editing the proposed text).
         */
        AcceptedBullet: {
            /** Source Id */
            source_id: string;
            /** Text */
            text: string;
        };
        /**
         * Application
         * @description A single tracked job application (no secrets/PII beyond what the user enters).
         */
        Application: {
            /**
             * Application Id
             * Format: uuid
             * @description Stable identifier
             */
            application_id?: string;
            /**
             * Company
             * @description Employer / organisation name
             * @default
             */
            company: string;
            /**
             * Job Title
             * @description Role title applied for
             * @default
             */
            job_title: string;
            /**
             * @description Application lifecycle status
             * @default applied
             */
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Applied On
             * @description ISO date (YYYY-MM-DD) the application was submitted; set at the boundary, never via datetime.now() in logic. Drives the 14-day sweep.
             * @default
             */
            applied_on: string;
            /**
             * Jd Text
             * @description Cleaned job-description text this application was tailored against
             * @default
             */
            jd_text: string;
            /**
             * Tailored Resume Json
             * @description The tailored resume variant used for this application (JSON)
             * @default
             */
            tailored_resume_json: string;
        };
        /**
         * ApplicationStatus
         * @description Lifecycle status of a tracked job application.
         * @enum {string}
         */
        ApplicationStatus: "applied" | "interview" | "offer" | "rejected" | "withdrawn";
        /**
         * ApplicationWriteRequest
         * @description Request body for ``POST /api/applications`` (api-local, not ``schema.py``).
         *
         *     A strict, no-extra-fields DTO the endpoint maps onto the existing
         *     ``web.application_store.save_tailored_application`` seam. ``applied_on`` is NOT
         *     part of the request: it is the injected clock computed at the endpoint boundary
         *     (``datetime.date.today()``), never supplied by the caller.
         */
        ApplicationWriteRequest: {
            /** Company */
            company: string;
            /** Job Title */
            job_title: string;
            /** Jd Text */
            jd_text: string;
            /** Tailored Resume Json */
            tailored_resume_json: string;
        };
        /** Body_seed_from_resume_api_grill_resume_post */
        Body_seed_from_resume_api_grill_resume_post: {
            /** File */
            file: string;
        };
        /**
         * Bullet
         * @description One line on an experience — with IDENTITY (contract v2.9.0, AD-18.3).
         *
         *     Bullets used to be bare strings, which made two things impossible:
         *
         *     - **Stable addressing.** Edits and deletes were addressed by ARRAY INDEX, which
         *       shifts under any concurrent insert or delete — so a slow client could edit the
         *       wrong line.
         *     - **Provenance.** There was no way to say "this reworded line REPLACES that original
         *       one", so the user could not be offered the overwrite-vs-keep-both choice, and the
         *       résumé assembler had to guess (by text similarity) whether two bullets said the
         *       same thing.
         *
         *     ``supersedes`` is what makes the copywriter loop (AD-18.2) and the résumé merge/dedup
         *     honest: a superseded bullet is dropped by ID, never by guessing at wording.
         */
        Bullet: {
            /**
             * Bullet Id
             * Format: uuid
             * @description Stable identifier for this bullet (UUID)
             */
            bullet_id?: string;
            /**
             * Text
             * @description The bullet's text as it appears on the résumé
             */
            text: string;
            /**
             * @description Where this bullet's text came from
             * @default parsed
             */
            source: components["schemas"]["BulletSource"];
            /**
             * Supersedes
             * @description The bullet_id this one REPLACES (a reworded/strengthened version of it). A superseded bullet is dropped from the résumé by id — never by guessing at text similarity.
             */
            supersedes?: string | null;
        };
        /**
         * BulletAddRequest
         * @description Request body for ``POST /api/experience/{entry_id}/bullet`` — append a bullet.
         *
         *     ``text`` is stripped before the length check for the same reason as
         *     ``BulletEditRequest.new_text`` below: the store strips it too, so a blank line would
         *     be a silently-dropped write reported to the UI as a success.
         */
        BulletAddRequest: {
            /** Text */
            text: string;
        };
        /**
         * BulletCardResponse
         * @description Mirror of :class:`web.portfolio.BulletCard` — a bullet WITH its id (v2.9.0).
         */
        BulletCardResponse: {
            /** Bullet Id */
            bullet_id: string;
            /** Text */
            text: string;
        };
        /**
         * BulletEditRequest
         * @description Request body for ``PATCH /api/experience/{entry_id}/bullet`` (parity P5).
         *
         *     ``new_text`` is stripped BEFORE the length check, so a whitespace-only edit is a 422
         *     rather than a silent no-op: the store strips it too, and would otherwise leave the
         *     bullet untouched while the endpoint reported 204.
         *
         *     Addressed by ``bullet_id``, not by array index (v2.9.0, AD-18.3) — an index shifts
         *     under any concurrent insert/delete, so a slow client could edit the wrong line.
         */
        BulletEditRequest: {
            /** Bullet Id */
            bullet_id: string;
            /** New Text */
            new_text: string;
        };
        /**
         * BulletSource
         * @description Where a bullet's text came from — its provenance.
         * @enum {string}
         */
        BulletSource: "parsed" | "user" | "grilled";
        /**
         * ContactDTO
         * @description Résumé header identity (mirrors ``web.resume_builder.Contact``).
         */
        ContactDTO: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Links */
            links?: string[];
        };
        /**
         * CopyProposalResponse
         * @description One proposed rewrite from the copywriter (CQ-4), linked to what it came from.
         */
        CopyProposalResponse: {
            /** Source Id */
            source_id: string;
            /** Text */
            text: string;
            /** Original */
            original: string;
        };
        /**
         * CopyProposalsResponse
         * @description Response for ``POST /api/experience/{entry_id}/copywrite``.
         */
        CopyProposalsResponse: {
            /** Proposals */
            proposals: components["schemas"]["CopyProposalResponse"][];
        };
        /**
         * DashboardResponse
         * @description Mirror of :class:`web.dashboard.DashboardView` (display-ready).
         */
        DashboardResponse: {
            /** Progress Meter */
            progress_meter: string;
            /** Show Nudge */
            show_nudge: boolean;
            /** Nudge Message */
            nudge_message: string;
            /** Pending Actions */
            pending_actions: string[];
            /** Application Count */
            application_count: number;
            /** Can Tailor */
            can_tailor: boolean;
            /** Can Start Grill */
            can_start_grill: boolean;
            /** Can Find Jobs */
            can_find_jobs: boolean;
            /** Pending Actions Detail */
            pending_actions_detail: {
                [key: string]: string;
            }[];
        };
        /**
         * DismissCompanyRequest
         * @description Request body for ``POST /api/jobs/dismiss`` (parity P5).
         *
         *     Dismissal is by COMPANY, not by job: the discovery ledger hard-rejects the company
         *     on future runs (``discovery.store.add_rejected_company``), which is what the old
         *     "Not interested" affordance did.
         *
         *     ``company`` is stripped before the length check (same reason as ``new_text`` above —
         *     the ledger strips it, so a blank name would be a silently-dropped dismissal).
         */
        DismissCompanyRequest: {
            /** Company */
            company: string;
        };
        /**
         * Entry
         * @description A single career experience entry in the work timeline.
         *
         *     The grillable unit of discovery: a job, internship, project, research
         *     engagement, open-source contribution, leadership role, or education item.
         */
        Entry: {
            /**
             * Entry Id
             * Format: uuid
             * @description Stable identifier for this entry (UUID)
             */
            entry_id?: string;
            /**
             * @description Category of experience (full_time, project, education, etc.)
             * @default other
             */
            type: components["schemas"]["ExperienceType"];
            /**
             * Title
             * @description Role/project title (e.g. 'Senior Engineer', 'Capstone Project')
             */
            title: string;
            /**
             * Org
             * @description Organisation, school, or team name
             * @default
             */
            org: string;
            /**
             * Start Date
             * @description Start date in YYYY-MM or YYYY format; empty means unknown
             * @default
             */
            start_date: string;
            /**
             * End Date
             * @description End date in YYYY-MM or YYYY format; empty string means 'present'
             * @default
             */
            end_date: string;
            /**
             * Source
             * @description How this entry entered the timeline
             * @default manual
             * @enum {string}
             */
            source: "resume" | "discovered" | "manual";
            /**
             * Bullets
             * @description Existing resume bullets or notes for this entry (v2.9.0: identified)
             */
            bullets?: components["schemas"]["Bullet"][];
            /**
             * @description Processing status of this entry in the discovery pipeline
             * @default needs_quantifying
             */
            status: components["schemas"]["EntryStatus"];
            /**
             * Highlighted
             * @description User pinned this experience as tailoring priority (4E, additive v2.7.0): its quantified achievements are always included when tailoring to a JD.
             * @default false
             */
            highlighted: boolean;
        };
        /**
         * EntryCardResponse
         * @description Mirror of :class:`web.portfolio.EntryCard`.
         */
        EntryCardResponse: {
            /** Entry Id */
            entry_id: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Dates */
            dates: string;
            /** Type Label */
            type_label: string;
            /** Status Label */
            status_label: string;
            /** Bullets */
            bullets: components["schemas"]["BulletCardResponse"][];
            /** Stories */
            stories: components["schemas"]["StoryCardResponse"][];
            /** Highlighted */
            highlighted: boolean;
            /** Story Count */
            story_count: number;
            /** Stories Target */
            stories_target: number;
        };
        /**
         * EntryStatus
         * @description Processing status of an experience entry in the discovery pipeline.
         * @enum {string}
         */
        EntryStatus: "documented" | "needs_quantifying" | "grilled" | "summarized" | "skipped";
        /**
         * ExperienceType
         * @description Type of career experience entry being tracked.
         * @enum {string}
         */
        ExperienceType: "full_time" | "internship" | "project" | "research" | "open_source" | "leadership" | "part_time" | "education" | "other";
        /**
         * ExperienceWriteResponse
         * @description Response for ``POST /api/experience`` (api-local, not ``schema.py``).
         *
         *     Confirms the persisted manual entry by echoing its ``entry_id`` and the
         *     ``title``/``org`` re-read from the discovery session, plus the resulting
         *     ``entry_count``. If the write can't be re-read, the endpoint still returns the
         *     echoed ``entry_id`` (with the submitted ``title``/``org``) rather than 500.
         */
        ExperienceWriteResponse: {
            /** Entry Id */
            entry_id: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Entry Count */
            entry_count: number;
        };
        /**
         * GrillActionRequest
         * @description Request body for ``POST /api/grill`` (api-local, not ``schema.py``).
         *
         *     Records the caller's input into the durable canonical session WITHOUT running
         *     the graph (the graph runs later on ``GET /api/grill/stream``). The user's answer
         *     travels in the body (never a URL query), so grill PII never lands in access logs.
         *
         *     - ``start`` uses ``history`` (+ optional ``reference_date``) to create the session.
         *     - ``answer`` uses ``answer`` (patched as ``pending_user_answer``).
         *     - ``confirm`` uses neither (sets ``checkpoint_verified``).
         */
        GrillActionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "answer" | "confirm";
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * History
             * @default
             */
            history: string;
            /**
             * Reference Date
             * @default
             */
            reference_date: string;
        };
        /**
         * GrillSnapshot
         * @description Response for ``POST /api/grill``: a small post-record status snapshot.
         *
         *     Computed from the durable session AFTER the record (no turn was run), so the
         *     client can render the "currently grilling" banner + await state before opening
         *     the SSE stream.
         */
        GrillSnapshot: {
            /** Phase */
            phase: string;
            /** Frontier Label */
            frontier_label: string;
            /**
             * Awaiting
             * @enum {string}
             */
            awaiting: "question" | "checkpoint" | "complete";
        };
        /**
         * GrillStatus
         * @description Response for ``GET /api/grill``: does a durable grill session already exist?
         *
         *     Read-only and model-free — it reports what the session ALREADY holds
         *     (``current_question`` / ``checkpoint_delta_summary`` are persisted), so resuming a
         *     grill costs no model call and cannot re-ask a question the user already saw.
         *
         *     Without this the client had no way to know a session existed: the Grill page decided
         *     what to render purely from in-memory state, so a fresh page load always showed the
         *     "upload your résumé" start card — even with a live session full of ungrilled
         *     entries, and even when the user had just clicked "Grill me about this".
         */
        GrillStatus: {
            /** Has Session */
            has_session: boolean;
            /** Phase */
            phase: string;
            /** Frontier Label */
            frontier_label: string;
            /**
             * Awaiting
             * @enum {string}
             */
            awaiting: "idle" | "question" | "checkpoint" | "complete";
            /** Current Question */
            current_question: string;
            /** Checkpoint Summary */
            checkpoint_summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness response body.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * HighlightRequest
         * @description Request body for ``POST /api/experience/{entry_id}/highlight``.
         */
        HighlightRequest: {
            /** Highlighted */
            highlighted: boolean;
        };
        /**
         * JobCardResponse
         * @description Mirror of :class:`web.jobs.JobCard`.
         */
        JobCardResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Work Model */
            work_model: string;
            /** Employment Type */
            employment_type: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * JobsResponse
         * @description Mirror of :class:`web.jobs.JobsView` (``is_empty`` included).
         */
        JobsResponse: {
            /** Accepted */
            accepted: components["schemas"]["JobCardResponse"][];
            /** For Review */
            for_review: components["schemas"]["JobCardResponse"][];
            /** Iterations */
            iterations: number;
            /** Hard Rejected Count */
            hard_rejected_count: number;
            /** Ran */
            ran: boolean;
            /** Empty Text */
            empty_text: string;
            /** Is Empty */
            is_empty: boolean;
        };
        /**
         * KeyStatusResponse
         * @description Response for ``GET /api/key`` — whether the caller has a saved key. The raw
         *     key is NEVER returned.
         */
        KeyStatusResponse: {
            /** Has Key */
            has_key: boolean;
        };
        /**
         * KeyWriteRequest
         * @description Request body for ``POST /api/key`` — the user's raw Gemini API key (BYOK).
         *
         *     Never logged or echoed back; stored in Secret Manager (``ce-key-{user_id}``).
         */
        KeyWriteRequest: {
            /** Api Key */
            api_key: string;
        };
        /**
         * MeResponse
         * @description Verified identity response body (safe display info only).
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email?: string | null;
        };
        /**
         * PortfolioResponse
         * @description Mirror of :class:`web.portfolio.PortfolioView` (``is_empty`` included).
         */
        PortfolioResponse: {
            /** Entries */
            entries: components["schemas"]["EntryCardResponse"][];
            /** Empty Text */
            empty_text: string;
            /** Is Empty */
            is_empty: boolean;
        };
        /**
         * RoleBlockDTO
         * @description One experience/education entry (mirrors ``web.resume_builder.RoleBlock``).
         */
        RoleBlockDTO: {
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Dates */
            dates: string;
            /** Bullets */
            bullets?: string[];
        };
        /**
         * SessionPreferences
         * @description The evaluation rubric for a discovery session (gathered at intake).
         *
         *     ``dealbreakers`` are absolute (→ HARD_REJECT); ``nice_to_haves`` are soft
         *     (a miss → SOFT_REJECT, kept for review). No secrets. Persisted per user on
         *     ``UserWorkspace.discovery_preferences`` (v2.8.0) so it isn't re-entered.
         */
        SessionPreferences: {
            /**
             * Target Roles
             * @description Roles being targeted this session
             */
            target_roles?: string[];
            /**
             * Dealbreakers
             * @description Absolute exclusions (e.g. 'W2 only', 'on-site', 'no cloud')
             */
            dealbreakers?: string[];
            /**
             * Nice To Haves
             * @description Soft preferences (a miss is a SOFT_REJECT, not a drop)
             */
            nice_to_haves?: string[];
            /**
             * Contract Version
             * @default 2.9.0
             */
            contract_version: string;
        };
        /**
         * StoryCardResponse
         * @description Mirror of :class:`web.portfolio.StoryCard`.
         */
        StoryCardResponse: {
            /** Situation */
            situation: string;
            /** Task */
            task: string;
            /** Action */
            action: string;
            /** Result */
            result: string;
            /** Metric Validated */
            metric_validated: boolean;
            /** Story Id */
            story_id: string;
        };
        /**
         * StructuredResumeDTO
         * @description A real résumé (mirrors ``web.resume_builder.StructuredResume``).
         *
         *     Response of ``POST /api/tailor`` and request body of ``POST /api/resume/{fmt}``.
         */
        StructuredResumeDTO: {
            contact: components["schemas"]["ContactDTO"];
            /** Summary */
            summary: string;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["RoleBlockDTO"][];
            /** Education */
            education?: components["schemas"]["RoleBlockDTO"][];
        };
        /**
         * TailorRequest
         * @description Request body for ``POST /api/tailor``.
         *
         *     ``jd_text`` is the already-resolved job description; ``instructions`` are placed
         *     in the *user* prompt (injection-safe, per 9I) and never persisted; ``contact``
         *     optionally overrides the résumé header (else an empty header).
         */
        TailorRequest: {
            /** Jd Text */
            jd_text: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            contact?: components["schemas"]["ContactDTO"] | null;
        };
        /**
         * UserProfile
         * @description The user's résumé-header identity, persisted so it isn't re-entered.
         *
         *     Sourced from what the user types in the Tailor contact form (and, later, from
         *     résumé parsing). Contains only self-provided contact details — no secrets, no
         *     BYOK key. Optional/empty for a new user.
         */
        UserProfile: {
            /**
             * Name
             * @description Full name for the résumé header
             * @default
             */
            name: string;
            /**
             * Email
             * @description Contact email
             * @default
             */
            email: string;
            /**
             * Phone
             * @description Contact phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @description Location string (e.g. 'Remote · US')
             * @default
             */
            location: string;
            /**
             * Links
             * @description Profile links (LinkedIn, GitHub, portfolio)
             */
            links?: string[];
            /**
             * Contract Version
             * @default 2.9.0
             */
            contract_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_endpoint_api_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_preferences_endpoint_api_preferences_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_application_endpoint_api_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_experience_endpoint_api_experience_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Entry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grill_status_api_grill_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrillStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_grill_action_api_grill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrillActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrillSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_from_resume_api_grill_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_seed_from_resume_api_grill_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrillSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_grill_turns_api_grill_stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_api_tailor_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredResumeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    master_resume_api_master_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredResumeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_resume_api_resume__fmt__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                fmt: "pdf" | "docx" | "md";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredResumeDTO"];
            };
        };
        responses: {
            /** @description The rendered résumé bytes for the requested format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    key_status_api_key_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_key_api_key_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_key_api_key_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_jobs_api_jobs_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_company_api_jobs_dismiss_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissCompanyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grill_entry_api_experience__entry_id__grill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    highlight_entry_api_experience__entry_id__highlight_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_bullet_api_experience__entry_id__bullet_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulletAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_bullet_api_experience__entry_id__bullet_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulletEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_bullet_api_experience__entry_id__bullet__bullet_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
                bullet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_entry_api_experience__entry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_story_api_story__story_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copywrite_api_experience__entry_id__copywrite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyProposalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_copywritten_bullets_api_experience__entry_id__bullets_accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptBulletsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
